name: unitary

on:
  pull_request_target:
  push:
    branches:
      - master

jobs:
  unitary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]

    name: "unit tests: python ${{ matrix.python-version }}"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - name: Merge base branch
        if: github.event_name == 'pull_request_target'
        run: |
          git fetch origin ${{ github.base_ref }}
          git merge ${{ github.base_ref }} --no-edit
